// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAppPrj.Data;

#nullable disable

namespace StudentAppPrj.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("StudentAppPrj.Models.Department", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaKhoa");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("StudentAppPrj.Models.Student", b =>
                {
                    b.Property<int>("MaSV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaKhoa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaSV");

                    b.HasIndex("MaKhoa");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("StudentAppPrj.Models.Student", b =>
                {
                    b.HasOne("StudentAppPrj.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("MaKhoa");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentAppPrj.Models.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
